// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="example_example,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1664,HLS_SYN_LUT=2053,HLS_VERSION=2021_1}" *)

module example (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        inStreamTop_TDATA,
        inStreamTop_TKEEP,
        inStreamTop_TSTRB,
        inStreamTop_TLAST,
        inStreamTop_TVALID,
        inStreamTop_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
input  [63:0] inStreamTop_TDATA;
input  [7:0] inStreamTop_TKEEP;
input  [7:0] inStreamTop_TSTRB;
input  [0:0] inStreamTop_TLAST;
input   inStreamTop_TVALID;
output   inStreamTop_TREADY;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] outTop;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [63:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire   [63:0] entry_proc_U0_ap_return;
wire    outTop_c_channel_full_n;
wire    getinstream_U0_ap_start;
wire    getinstream_U0_ap_done;
wire    getinstream_U0_ap_continue;
wire    getinstream_U0_ap_idle;
wire    getinstream_U0_ap_ready;
wire   [127:0] getinstream_U0_buf_r_din;
wire    getinstream_U0_buf_r_write;
wire   [31:0] getinstream_U0_count7_din;
wire    getinstream_U0_count7_write;
wire    getinstream_U0_inStreamTop_TREADY;
wire    streamtoparallelwithburst_U0_ap_start;
wire    streamtoparallelwithburst_U0_ap_done;
wire    streamtoparallelwithburst_U0_ap_continue;
wire    streamtoparallelwithburst_U0_ap_idle;
wire    streamtoparallelwithburst_U0_ap_ready;
wire    streamtoparallelwithburst_U0_buf_r_read;
wire    streamtoparallelwithburst_U0_count7_read;
wire    streamtoparallelwithburst_U0_m_axi_gmem0_AWVALID;
wire   [63:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWADDR;
wire   [0:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWID;
wire   [31:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWLEN;
wire   [2:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWBURST;
wire   [1:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWPROT;
wire   [3:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWQOS;
wire   [3:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWREGION;
wire   [0:0] streamtoparallelwithburst_U0_m_axi_gmem0_AWUSER;
wire    streamtoparallelwithburst_U0_m_axi_gmem0_WVALID;
wire   [63:0] streamtoparallelwithburst_U0_m_axi_gmem0_WDATA;
wire   [7:0] streamtoparallelwithburst_U0_m_axi_gmem0_WSTRB;
wire    streamtoparallelwithburst_U0_m_axi_gmem0_WLAST;
wire   [0:0] streamtoparallelwithburst_U0_m_axi_gmem0_WID;
wire   [0:0] streamtoparallelwithburst_U0_m_axi_gmem0_WUSER;
wire    streamtoparallelwithburst_U0_m_axi_gmem0_ARVALID;
wire   [63:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARADDR;
wire   [0:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARID;
wire   [31:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARLEN;
wire   [2:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARBURST;
wire   [1:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARPROT;
wire   [3:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARQOS;
wire   [3:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARREGION;
wire   [0:0] streamtoparallelwithburst_U0_m_axi_gmem0_ARUSER;
wire    streamtoparallelwithburst_U0_m_axi_gmem0_RREADY;
wire    streamtoparallelwithburst_U0_m_axi_gmem0_BREADY;
wire   [63:0] outTop_c_channel_dout;
wire    outTop_c_channel_empty_n;
wire    buf_full_n;
wire   [127:0] buf_dout;
wire    buf_empty_n;
wire    count_full_n;
wire   [31:0] count_dout;
wire    count_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_getinstream_U0_ap_ready;
wire    ap_sync_getinstream_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_getinstream_U0_ap_ready = 1'b0;
end

example_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .outTop(outTop),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

example_gmem0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 15 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 256 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(streamtoparallelwithburst_U0_m_axi_gmem0_AWVALID),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(streamtoparallelwithburst_U0_m_axi_gmem0_AWADDR),
    .I_AWID(streamtoparallelwithburst_U0_m_axi_gmem0_AWID),
    .I_AWLEN(streamtoparallelwithburst_U0_m_axi_gmem0_AWLEN),
    .I_AWSIZE(streamtoparallelwithburst_U0_m_axi_gmem0_AWSIZE),
    .I_AWLOCK(streamtoparallelwithburst_U0_m_axi_gmem0_AWLOCK),
    .I_AWCACHE(streamtoparallelwithburst_U0_m_axi_gmem0_AWCACHE),
    .I_AWQOS(streamtoparallelwithburst_U0_m_axi_gmem0_AWQOS),
    .I_AWPROT(streamtoparallelwithburst_U0_m_axi_gmem0_AWPROT),
    .I_AWUSER(streamtoparallelwithburst_U0_m_axi_gmem0_AWUSER),
    .I_AWBURST(streamtoparallelwithburst_U0_m_axi_gmem0_AWBURST),
    .I_AWREGION(streamtoparallelwithburst_U0_m_axi_gmem0_AWREGION),
    .I_WVALID(streamtoparallelwithburst_U0_m_axi_gmem0_WVALID),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(streamtoparallelwithburst_U0_m_axi_gmem0_WDATA),
    .I_WID(streamtoparallelwithburst_U0_m_axi_gmem0_WID),
    .I_WUSER(streamtoparallelwithburst_U0_m_axi_gmem0_WUSER),
    .I_WLAST(streamtoparallelwithburst_U0_m_axi_gmem0_WLAST),
    .I_WSTRB(streamtoparallelwithburst_U0_m_axi_gmem0_WSTRB),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(streamtoparallelwithburst_U0_m_axi_gmem0_BREADY),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

example_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .outTop(outTop),
    .ap_return(entry_proc_U0_ap_return)
);

example_getinstream getinstream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(getinstream_U0_ap_start),
    .ap_done(getinstream_U0_ap_done),
    .ap_continue(getinstream_U0_ap_continue),
    .ap_idle(getinstream_U0_ap_idle),
    .ap_ready(getinstream_U0_ap_ready),
    .inStreamTop_TVALID(inStreamTop_TVALID),
    .buf_r_din(getinstream_U0_buf_r_din),
    .buf_r_full_n(buf_full_n),
    .buf_r_write(getinstream_U0_buf_r_write),
    .count7_din(getinstream_U0_count7_din),
    .count7_full_n(count_full_n),
    .count7_write(getinstream_U0_count7_write),
    .inStreamTop_TDATA(inStreamTop_TDATA),
    .inStreamTop_TREADY(getinstream_U0_inStreamTop_TREADY),
    .inStreamTop_TKEEP(inStreamTop_TKEEP),
    .inStreamTop_TSTRB(inStreamTop_TSTRB),
    .inStreamTop_TLAST(inStreamTop_TLAST)
);

example_streamtoparallelwithburst streamtoparallelwithburst_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(streamtoparallelwithburst_U0_ap_start),
    .ap_done(streamtoparallelwithburst_U0_ap_done),
    .ap_continue(streamtoparallelwithburst_U0_ap_continue),
    .ap_idle(streamtoparallelwithburst_U0_ap_idle),
    .ap_ready(streamtoparallelwithburst_U0_ap_ready),
    .buf_r_dout(buf_dout),
    .buf_r_empty_n(buf_empty_n),
    .buf_r_read(streamtoparallelwithburst_U0_buf_r_read),
    .count7_dout(count_dout),
    .count7_empty_n(count_empty_n),
    .count7_read(streamtoparallelwithburst_U0_count7_read),
    .m_axi_gmem0_AWVALID(streamtoparallelwithburst_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(gmem0_AWREADY),
    .m_axi_gmem0_AWADDR(streamtoparallelwithburst_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(streamtoparallelwithburst_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(streamtoparallelwithburst_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(streamtoparallelwithburst_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(streamtoparallelwithburst_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(streamtoparallelwithburst_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(streamtoparallelwithburst_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(streamtoparallelwithburst_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(streamtoparallelwithburst_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(streamtoparallelwithburst_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(streamtoparallelwithburst_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(streamtoparallelwithburst_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(gmem0_WREADY),
    .m_axi_gmem0_WDATA(streamtoparallelwithburst_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(streamtoparallelwithburst_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(streamtoparallelwithburst_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(streamtoparallelwithburst_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(streamtoparallelwithburst_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(streamtoparallelwithburst_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(1'b0),
    .m_axi_gmem0_ARADDR(streamtoparallelwithburst_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(streamtoparallelwithburst_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(streamtoparallelwithburst_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(streamtoparallelwithburst_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(streamtoparallelwithburst_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(streamtoparallelwithburst_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(streamtoparallelwithburst_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(streamtoparallelwithburst_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(streamtoparallelwithburst_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(streamtoparallelwithburst_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(streamtoparallelwithburst_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(1'b0),
    .m_axi_gmem0_RREADY(streamtoparallelwithburst_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(64'd0),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(gmem0_BVALID),
    .m_axi_gmem0_BREADY(streamtoparallelwithburst_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(gmem0_BRESP),
    .m_axi_gmem0_BID(gmem0_BID),
    .m_axi_gmem0_BUSER(gmem0_BUSER),
    .p_read(outTop_c_channel_dout)
);

example_fifo_w64_d2_S outTop_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ap_return),
    .if_full_n(outTop_c_channel_full_n),
    .if_write(entry_proc_U0_ap_done),
    .if_dout(outTop_c_channel_dout),
    .if_empty_n(outTop_c_channel_empty_n),
    .if_read(streamtoparallelwithburst_U0_ap_ready)
);

example_fifo_w128_d4096_A buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(getinstream_U0_buf_r_din),
    .if_full_n(buf_full_n),
    .if_write(getinstream_U0_buf_r_write),
    .if_dout(buf_dout),
    .if_empty_n(buf_empty_n),
    .if_read(streamtoparallelwithburst_U0_buf_r_read)
);

example_fifo_w32_d64_A count_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(getinstream_U0_count7_din),
    .if_full_n(count_full_n),
    .if_write(getinstream_U0_count7_write),
    .if_dout(count_dout),
    .if_empty_n(count_empty_n),
    .if_read(streamtoparallelwithburst_U0_count7_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_getinstream_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_getinstream_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_getinstream_U0_ap_ready <= ap_sync_getinstream_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign ap_done = streamtoparallelwithburst_U0_ap_done;

assign ap_idle = (streamtoparallelwithburst_U0_ap_idle & getinstream_U0_ap_idle & (outTop_c_channel_empty_n ^ 1'b1) & entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_getinstream_U0_ap_ready = (getinstream_U0_ap_ready | ap_sync_reg_getinstream_U0_ap_ready);

assign ap_sync_ready = (ap_sync_getinstream_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign entry_proc_U0_ap_continue = outTop_c_channel_full_n;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign getinstream_U0_ap_continue = 1'b1;

assign getinstream_U0_ap_start = ((ap_sync_reg_getinstream_U0_ap_ready ^ 1'b1) & ap_start);

assign inStreamTop_TREADY = getinstream_U0_inStreamTop_TREADY;

assign streamtoparallelwithburst_U0_ap_continue = ap_continue;

assign streamtoparallelwithburst_U0_ap_start = outTop_c_channel_empty_n;

endmodule //example
